### ISSUE TITLE
NOT WORK IN WINDOWS

### ISSUE THREAD

**Issue by ComandPromt** [francescovannini/photoslicer#1]
NOT WORK IN WINDOWS

**Comment by francescovannini** [comment]
It's indeed possible, I've never tried running it on Windows. If you have more details about the issues you've faced and you feel like sharing them, I can have a look. Thanks!

**Comment by ComandPromt** [comment]
> It's indeed possible, I've never tried running it on Windows. If you have more details about the issues you've faced and you feel like sharing them, I can have a look. Thanks!

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\__main__.py", line 204, in open_directory
    self.load_image(0)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\__main__.py", line 126, in load_image
    self.autoslicer.load_image(self.source_images[self.source_index])
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\autoslicer.py", line 54, in load_image
    self.image_gray = cv2.cvtColor(self.image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\slicingcanvas.py", line 193, in mouse_wheel
    bbox = self.bbox(self.picture_frame)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2731, in bbox
    self.tk.call((self._w, 'bbox') + args)) or None
_tkinter.TclError: wrong # args: should be ".!photoslicer.!slicingcanvas bbox tagOrId ?tagOrId ...?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\slicingcanvas.py", line 193, in mouse_wheel
    bbox = self.bbox(self.picture_frame)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2731, in bbox
    self.tk.call((self._w, 'bbox') + args)) or None
_tkinter.TclError: wrong # args: should be ".!photoslicer.!slicingcanvas bbox tagOrId ?tagOrId ...?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\slicingcanvas.py", line 193, in mouse_wheel
    bbox = self.bbox(self.picture_frame)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2731, in bbox
    self.tk.call((self._w, 'bbox') + args)) or None
_tkinter.TclError: wrong # args: should be ".!photoslicer.!slicingcanvas bbox tagOrId ?tagOrId ...?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\slicingcanvas.py", line 193, in mouse_wheel
    bbox = self.bbox(self.picture_frame)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2731, in bbox
    self.tk.call((self._w, 'bbox') + args)) or None
_tkinter.TclError: wrong # args: should be ".!photoslicer.!slicingcanvas bbox tagOrId ?tagOrId ...?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\slicingcanvas.py", line 193, in mouse_wheel
    bbox = self.bbox(self.picture_frame)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2731, in bbox
    self.tk.call((self._w, 'bbox') + args)) or None
_tkinter.TclError: wrong # args: should be ".!photoslicer.!slicingcanvas bbox tagOrId ?tagOrId ...?"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\User\3D Objects\photoslicer-master\photoslicer-master\photoslicer\slicingcanvas.py", line 193, in mouse_wheel
    bbox = self.bbox(self.picture_frame)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2731, in bbox
    self.tk.call((self._w, 'bbox') + args)) or None
_tkinter.TclError: wrong # args: should be ".!photoslicer.!slicingcanvas bbox tagOrId ?tagOrId ...?"
